name: simple_devops_project
services:
  python_app:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports: 
      - 8000:8000
    environment:
      - DB_HOST=postgres_db
    env_file:
      - ./.env
    secrets:
      - db_pass
    healthcheck:
      test: ["CMD", "wget", "-q", "--spider", "http://localhost:8000/healthy"]
      interval: 5s
      timeout: 10s
      retries: 3
      start_period: 10s
    depends_on:
      postgres_db:
        condition: service_healthy
        restart: true
  postgres_db:
    image: postgres:17.10-alpine3.23
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/db_pass
    env_file:
      - ./.env
    secrets:
      - db_pass
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 10s
      retries: 5
      start_period: 10s
    volumes:
      - db-data:/var/lib/postgresql/data

secrets:
  db_pass:
    file: ./secrets/db_pass.txt

volumes:
  db-data: